image: alpine/helm

variables:
  SERVICE_NAME: frame-channel
  REPO: asia-southeast2-docker.pkg.dev/finnet-artifact/finpay-billing
  NAMESPACE: finpay-billing

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:20-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false","--mtu=1300"]
  before_script:
    - cat $GCP_KEYS_DEV | docker login -u _json_key --password-stdin https://$REPO
    - if [ "$CI_COMMIT_BRANCH" ==  "master" ]; then VERSION=$CI_PIPELINE_IID; else VERSION=$CI_COMMIT_TAG; fi;
  only:
    refs:
      - tags
      - master
  script:
    - docker build -t $SERVICE_NAME:$VERSION .
    - docker image ls
    - docker tag $SERVICE_NAME:$VERSION $REPO/$SERVICE_NAME:$VERSION
    - docker push $REPO/$SERVICE_NAME:$VERSION
    - docker logout https://$REPO

.deploy_template: &deploy
  script:
    - sed -i "s|APP_VERSION|$VERSION|g" src/helm/Chart.yaml
    - sed -i "s|VAR_LOADBALANCER_IP|$VAR_LOADBALANCER_IP|g" src/helm/Frame-channel.yaml
    - sed -i "s|VAR_SERVICE_NAME|$SERVICE_NAME|g" src/helm/Frame-channel.yaml
    - sed -i "s|VAR_SERVER_ADDRESS|$SERVER_ADDRESS|g" src/helm/Frame-channel.yaml
    - sed -i "s|VAR_SERVER_PORT|$SERVER_PORT|g" src/helm/Frame-channel.yaml
    - sed -i "s|VAR_TS_URL|$TS_URL|g" src/helm/Frame-channel.yaml
    - sed -i "s|VAR_NEVA_URL|$NEVA_URL|g" src/helm/Frame-channel.yaml
    - sed -i "s|VAR_DB_USER|$DB_USER|g" src/helm/Frame-channel.yaml
    - sed -i "s|VAR_DB_PASS|$DB_PASS|g" src/helm/Frame-channel.yaml
    - sed -i "s|VAR_DB_ADDRESS|$DB_ADDRESS|g" src/helm/Frame-channel.yaml
    - sed -i "s|VAR_DB_PORT|$DB_PORT|g" src/helm/Frame-channel.yaml
    - sed -i "s|VAR_DB_NAME|$DB_NAME|g" src/helm/Frame-channel.yaml
    - sed -i "s|VAR_LOG_TIME_FORMAT|$LOG_TIME_FORMAT|g" src/helm/Frame-channel.yaml
    - sed -i "s|VAR_LOG_BEAUTIFY|$LOG_BEAUTIFY|g" src/helm/Frame-channel.yaml
    - sed -i "s|VAR_LOG_OUTPUT|$LOG_OUTPUT|g" src/helm/Frame-channel.yaml
    - sed -i "s|VAR_GIN_MODE|$GIN_MODE|g" src/helm/Frame-channel.yaml
    - sed -i "s|VAR_ENV|$ENV|g" src/helm/Frame-channel.yaml
    - helm upgrade --install $SERVICE_NAME src/helm -f src/helm/Frame-channel.yaml -n $NAMESPACE --wait --timeout 2m0s
  when: on_success
  allow_failure: false    


deploy_staging:
  <<: *deploy
  stage: deploy
  environment:
    name: staging  
  variables:
    VERSION: $CI_PIPELINE_IID
    DEPLOY_ENVIRONMENT: dev
  after_script:
    - less src/helm/Chart.yaml
    - less src/helm/Frame-channel.yaml
  only:
    refs:
      - master
  tags:
    - kubedev

deploy_production:
  <<: *deploy
  stage: deploy
  environment:
    name: production
  when: manual
  variables:
    VERSION: $CI_COMMIT_TAG
  after_script:
    - less src/helm/Chart.yaml
    - less src/helm/Frame-channel.yaml    
  only:
    refs:
      - tags
  tags:
    - kubeprod