apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-env
type: Opaque  
data:
  SERVER_ADDRESS: {{ .Values.env.SERVER_ADDRESS | b64enc | quote }}
  SERVER_PORT: {{ .Values.env.SERVER_PORT | b64enc | quote }}
  TS_URL: {{ .Values.env.TS_URL | b64enc | quote }}
  EVA_URL: {{ .Values.env.EVA_URL | b64enc | quote }}
  DB_USER: {{ .Values.env.DB_USER | b64enc | quote }}
  DB_PASS: {{ .Values.env.DB_PASS | b64enc | quote }}
  DB_ADDRESS: {{ .Values.env.DB_ADDRESS | b64enc | quote }}
  DB_PORT: {{ .Values.env.DB_PORT | b64enc | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | b64enc | quote }}
  LOG_TIME_FORMAT: {{ .Values.env.LOG_TIME_FORMAT | b64enc | quote }}
  LOG_BEAUTIFY: {{ .Values.env.LOG_BEAUTIFY | b64enc | quote }}
  LOG_OUTPUT: {{ .Values.env.LOG_OUTPUT | b64enc | quote }}
  GIN_MODE: {{ .Values.env.GIN_MODE | b64enc | quote }}
  ENV: {{ .Values.env.ENV | b64enc | quote }}