apiVersion: v1
kind: Service
metadata:
  name: {{ include "alfamart-channel.fullname" . }}
  labels:
    {{- include "alfamart-channel.labels" . | nindent 4 }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "alfamart-channel.selectorLabels" . | nindent 4 }}
